import { supabase } from "@/integrations/supabase/client";
export interface QualityRunRow{id:string;name:string;status:string;environment_name:string|null;build_reference:string|null;started_at:string|null;completed_at:string|null;created_at:string}
export async function listTestRuns(org:string){const {data,error}=await supabase.from("quality_test_runs").select("id,name,status,environment_name,build_reference,started_at,completed_at,created_at").eq("organization_id",org).order("created_at",{ascending:false});if(error)throw error;return(data??[]) as QualityRunRow[];}
export async function getTestRun(org:string,id:string){const {data,error}=await supabase.from("quality_test_runs").select("*,quality_test_run_items(*,quality_test_step_results(*),quality_test_evidences(*))").eq("organization_id",org).eq("id",id).order("sort_order",{referencedTable:"quality_test_run_items"}).single();if(error)throw error;return data;}
export async function startRun(org:string,id:string){const{error}=await supabase.rpc("start_quality_test_run_v1",{p_org_id:org,p_run_id:id});if(error)throw error;}
export async function updateStep(org:string,id:string,status:string,actual:string){const{error}=await supabase.rpc("update_quality_step_result_v1",{p_org_id:org,p_step_result_id:id,p_status:status,p_actual_result:actual});if(error)throw error;}
export async function addEvidence(org:string,itemId:string,stepId:string,title:string,url:string){const{error}=await supabase.rpc("add_quality_external_evidence_v1",{p_org_id:org,p_run_item_id:itemId,p_step_result_id:stepId,p_title:title,p_external_url:url});if(error)throw error;}
export async function completeRun(org:string,id:string,allow=false){const{error}=await supabase.rpc("complete_quality_test_run_v1",{p_org_id:org,p_run_id:id,p_allow_not_run:allow});if(error)throw error;}
export async function reopenRun(org:string,id:string,reason:string){const{error}=await supabase.rpc("reopen_quality_test_run_v1",{p_org_id:org,p_run_id:id,p_reason:reason});if(error)throw error;}
