import { AlertTriangle, Calculator, CheckCircle2, Loader2, Pencil } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useApfDossierCountingMemory } from "../../hooks/useApfEvidenceDossiers";
import { reviewApfCountingMetrics } from "../../services/apfEvidenceDossier.service";

export function ApfDossierCounting({ dossierId, sessionId }: { dossierId: string; sessionId: string | null }) {
  const { data: memory, isLoading, isError, refetch } = useApfDossierCountingMemory(sessionId);
  const reviewMetrics = async (item: NonNullable<typeof memory>["items"][number]) => { const values = window.prompt("Informe DET,FTR,RET", `${item.det ?? ""},${item.ftr ?? ""},${item.ret ?? ""}`); if (values === null) return; const note = window.prompt("Justificativa obrigatória da revisão"); if (!note?.trim()) return; const [det, ftr, ret] = values.split(",").map((value) => value.trim() === "" ? null : Number(value)); if ([det, ftr, ret].some((value) => value !== null && (!Number.isInteger(value) || value < 0))) { toast.error("Use números inteiros não negativos."); return; } try { await reviewApfCountingMetrics(dossierId, item.id, det, ftr, ret, note); await refetch(); toast.success("Métricas confirmadas."); } catch (error) { toast.error(error instanceof Error ? error.message : "Falha ao revisar métricas."); } };
  if (!sessionId) return <Card className="border-dashed"><CardContent className="py-10 text-center"><Calculator className="mx-auto mb-3 h-8 w-8 text-muted-foreground" /><p className="font-medium">Contagem ainda não vinculada</p><p className="text-sm text-muted-foreground">Vincule uma sessão APF para reutilizar os cálculos do motor contratual.</p></CardContent></Card>;
  if (isLoading) return <div className="flex min-h-32 items-center justify-center" role="status"><Loader2 className="mr-2 h-4 w-4 animate-spin motion-reduce:animate-none" />Carregando memória de cálculo…</div>;
  if (isError || !memory) return <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">Não foi possível carregar a sessão de contagem.</p>;
  return <section className="space-y-3" aria-labelledby="counting-title">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="counting-title" className="font-semibold">Contagem e memória de cálculo</h3><p className="text-sm text-muted-foreground">Sessão {memory.sessionId.slice(0, 8)} · {memory.sessionStatus}</p></div><div className="flex gap-2"><Badge variant={memory.closes ? "default" : "destructive"}>{memory.closes ? <CheckCircle2 className="mr-1 h-3.5 w-3.5" /> : <AlertTriangle className="mr-1 h-3.5 w-3.5" />}{memory.closes ? "Memória fechada" : "Total divergente"}</Badge><Button variant="outline" size="sm" onClick={() => { const selected = window.prompt(`Item para revisar (1-${memory.items.length})`, "1"); const item = memory.items[Number(selected) - 1]; if (item) void reviewMetrics(item); }} disabled={memory.items.length === 0}><Pencil className="mr-1 h-3.5 w-3.5" />Revisar DET/FTR/RET</Button></div></div>
    <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-3"><Metric label="Itens" value={String(memory.items.length)} /><Metric label="Soma das linhas" value={`${formatPf(memory.calculatedTotalPf)} PF`} /><Metric label="Total da sessão" value={`${formatPf(memory.sessionTotalPf)} PF`} /></CardContent></Card>
    <Card className="overflow-hidden"><CardHeader className="pb-3"><CardTitle className="text-sm">Linhas da contagem oficial</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-sm"><thead className="border-y bg-muted/50 text-left text-xs text-muted-foreground"><tr><Th>Processo/arquivo</Th><Th>Tipo</Th><Th>Impacto</Th><Th>DET</Th><Th>FTR</Th><Th>RET</Th><Th>Complexidade</Th><Th>PF base</Th><Th>Fator</Th><Th>PF impactado</Th><Th>Decisão</Th></tr></thead><tbody>{memory.items.map((item) => <tr key={item.id} className="border-b last:border-0"><Td><p className="max-w-64 font-medium">{item.description}</p>{item.huRef && <p className="text-xs text-muted-foreground">{item.huRef}</p>}</Td><Td>{item.functionType}</Td><Td>{item.impactFactor}</Td><Td>{item.det ?? "—"}</Td><Td>{item.ftr ?? "—"}</Td><Td>{item.ret ?? "—"}</Td><Td>{item.complexity}</Td><Td>{formatPf(item.basePf)}</Td><Td>{formatPf(item.contributionPercent)}%</Td><Td><span className="font-semibold tabular-nums">{formatPf(item.impactedPf)}</span>{item.hasHumanOverride && <Badge variant="outline" className="ml-2">override</Badge>}</Td><Td><Badge variant={item.isValidated ? "default" : "secondary"}>{item.decision}</Badge></Td></tr>)}</tbody><tfoot><tr className="bg-muted/30 font-semibold"><td colSpan={9} className="px-4 py-3 text-right">Total calculado</td><td className="px-4 py-3 tabular-nums">{formatPf(memory.calculatedTotalPf)} PF</td><td /></tr></tfoot></table></CardContent></Card>
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="text-lg font-semibold tabular-nums">{value}</p></div>; }
function Th({ children }: { children: ReactNode }) { return <th scope="col" className="whitespace-nowrap px-4 py-3 font-medium">{children}</th>; }
function Td({ children }: { children: ReactNode }) { return <td className="px-4 py-3 align-top">{children}</td>; }
function formatPf(value: number) { return value.toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
import type { ReactNode } from "react";
