import { CheckCircle2, CircleDashed, Loader2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { useApfEvidenceSources } from "../../hooks/useApfEvidenceDossiers";
import type { ApfAcceptanceCriterion } from "../../types/apfEvidenceDossier.types";

export function ApfDossierTraceability({ dossierId, criteria }: { dossierId: string; criteria: ApfAcceptanceCriterion[] }) {
  const { data: evidence = [], isLoading, isError } = useApfEvidenceSources(dossierId);
  if (isLoading) return <div className="flex min-h-32 items-center justify-center" role="status"><Loader2 className="mr-2 h-4 w-4 animate-spin motion-reduce:animate-none" />Montando matriz…</div>;
  if (isError) return <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">Falha ao montar a matriz de rastreabilidade.</p>;
  return <section className="space-y-3" aria-labelledby="traceability-title"><div><h3 id="traceability-title" className="font-semibold">Matriz CA × evidências</h3><p className="text-sm text-muted-foreground">Visão consolidada dos vínculos registrados no catálogo.</p></div><Card className="overflow-hidden"><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[700px] text-sm"><thead className="border-y bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">CA</th><th className="px-4 py-3">Critério</th><th className="px-4 py-3">Decisão</th><th className="px-4 py-3">Evidências</th><th className="px-4 py-3">Cobertura</th></tr></thead><tbody>{criteria.map((criterion) => { const linked = evidence.filter((item) => item.criterionIds.includes(criterion.id)); const verified = linked.some((item) => item.verificationStatus === "verified"); return <tr key={criterion.id} className="border-b last:border-0"><td className="px-4 py-3 font-mono text-xs">{criterion.stableId}</td><td className="max-w-sm px-4 py-3">{criterion.originalText}</td><td className="px-4 py-3"><Badge variant={criterion.decision ? "secondary" : "outline"}>{criterion.decision ?? "pendente"}</Badge></td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{linked.map((item) => <Badge key={item.id} variant="outline">{item.stableId}</Badge>)}{linked.length === 0 && "—"}</div></td><td className="px-4 py-3">{verified ? <span className="flex items-center gap-1 text-emerald-700 dark:text-emerald-400"><CheckCircle2 className="h-4 w-4" />Verificada</span> : <span className="flex items-center gap-1 text-muted-foreground"><CircleDashed className="h-4 w-4" />Pendente</span>}</td></tr>; })}</tbody></table></CardContent></Card></section>;
}
