import { useCallback, useEffect, useState } from "react";
import { Check, CheckCircle2, CircleDashed, Loader2, Sparkles, X } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useApfEvidenceSources } from "../../hooks/useApfEvidenceDossiers";
import { generateApfSemanticTraceabilitySuggestions, generateApfTraceabilitySuggestions, listApfTraceabilitySuggestions, reviewApfTraceabilitySuggestion } from "../../services/apfEvidenceDossier.service";
import type { ApfAcceptanceCriterion, ApfEvidenceSource, ApfTraceabilitySuggestion } from "../../types/apfEvidenceDossier.types";

export function ApfDossierTraceability({ dossierId, criteria }: { dossierId: string; criteria: ApfAcceptanceCriterion[] }) {
  const { data: evidence = [], isLoading, isError, refetch } = useApfEvidenceSources(dossierId);
  const [suggestions, setSuggestions] = useState<ApfTraceabilitySuggestion[]>([]);
  const [suggesting, setSuggesting] = useState(false);
  const [reviewingId, setReviewingId] = useState<string | null>(null);
  const [semanticSuggesting, setSemanticSuggesting] = useState(false);
  const loadSuggestions = useCallback(async () => setSuggestions(await listApfTraceabilitySuggestions(dossierId)), [dossierId]);
  useEffect(() => { void loadSuggestions().catch(() => undefined); }, [loadSuggestions]);
  const generate = async () => { setSuggesting(true); try { const count = await generateApfTraceabilitySuggestions(dossierId); await loadSuggestions(); toast.success(count ? `${count} sugestão(ões) atualizada(s).` : "Nenhuma correspondência verificável foi encontrada."); } catch (error) { toast.error(error instanceof Error ? error.message : "Falha ao gerar sugestões."); } finally { setSuggesting(false); } };
  const generateSemantic=async()=>{setSemanticSuggesting(true);try{const count=await generateApfSemanticTraceabilitySuggestions(dossierId);await loadSuggestions();toast.success(count?`${count} sugestão(ões) semântica(s) gerada(s).`:"A IA não encontrou vínculo sustentado suficiente.");}catch(error){toast.error(error instanceof Error?error.message:"Falha na análise semântica.");}finally{setSemanticSuggesting(false);}};
  const review = async (id: string, accept: boolean) => { setReviewingId(id); try { await reviewApfTraceabilitySuggestion(id, accept); await Promise.all([loadSuggestions(), refetch()]); toast.success(accept ? "Vínculo confirmado." : "Sugestão rejeitada."); } catch (error) { toast.error(error instanceof Error ? error.message : "Falha ao revisar sugestão."); } finally { setReviewingId(null); } };
  if (isLoading) return <div className="flex min-h-32 items-center justify-center" role="status"><Loader2 className="mr-2 h-4 w-4 animate-spin motion-reduce:animate-none" />Montando matriz…</div>;
  if (isError) return <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">Falha ao montar a matriz de rastreabilidade.</p>;
  return <section className="space-y-4" aria-labelledby="traceability-title">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 id="traceability-title" className="font-semibold">Matriz CA × evidências</h3><p className="text-sm text-muted-foreground">Vínculos confirmados e sugestões aguardando decisão humana.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void generate()} disabled={suggesting||semanticSuggesting||criteria.length===0||evidence.length===0}>{suggesting?<Loader2 className="mr-2 h-4 w-4 animate-spin motion-reduce:animate-none"/>:<Sparkles className="mr-2 h-4 w-4"/>}Análise lexical</Button><Button onClick={()=>void generateSemantic()} disabled={suggesting||semanticSuggesting||criteria.length===0||evidence.length===0}>{semanticSuggesting?<Loader2 className="mr-2 h-4 w-4 animate-spin motion-reduce:animate-none"/>:<Sparkles className="mr-2 h-4 w-4"/>}Análise semântica com IA</Button></div></div>
    {suggestions.length > 0 && <div className="space-y-2" aria-label="Sugestões pendentes"><h4 className="text-sm font-semibold">Revisão de sugestões ({suggestions.length})</h4>{suggestions.map((suggestion) => { const criterion = criteria.find((item) => item.id === suggestion.criterionId); const source = evidence.find((item) => item.id === suggestion.evidenceSourceId); return <Card key={suggestion.id}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{criterion?.stableId ?? "CA"}</Badge><span aria-hidden="true">→</span><Badge variant="secondary">{source?.stableId ?? "Evidência"}</Badge><Badge variant="outline">{Math.round(suggestion.confidence * 100)}%</Badge></div><p className="mt-2 text-sm">{suggestion.rationale}</p><p className="mt-1 truncate text-xs text-muted-foreground">{source?.summary}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => void review(suggestion.id, false)} disabled={reviewingId === suggestion.id}><X className="mr-1 h-4 w-4" />Rejeitar</Button><Button size="sm" onClick={() => void review(suggestion.id, true)} disabled={reviewingId === suggestion.id}>{reviewingId === suggestion.id ? <Loader2 className="mr-1 h-4 w-4 animate-spin motion-reduce:animate-none" /> : <Check className="mr-1 h-4 w-4" />}Confirmar</Button></div></CardContent></Card>; })}</div>}
    <TraceabilityTable criteria={criteria} evidence={evidence} />
  </section>;
}

function TraceabilityTable({ criteria, evidence }: { criteria: ApfAcceptanceCriterion[]; evidence: ApfEvidenceSource[] }) {
  return <Card className="overflow-hidden"><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[700px] text-sm"><thead className="border-y bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3">CA</th><th className="px-4 py-3">Critério</th><th className="px-4 py-3">Decisão</th><th className="px-4 py-3">Evidências</th><th className="px-4 py-3">Cobertura</th></tr></thead><tbody>{criteria.map((criterion) => { const linked = evidence.filter((item) => item.criterionIds.includes(criterion.id)); const verified = linked.some((item) => item.verificationStatus === "verified"); return <tr key={criterion.id} className="border-b last:border-0"><td className="px-4 py-3 font-mono text-xs">{criterion.stableId}</td><td className="max-w-sm px-4 py-3">{criterion.originalText}</td><td className="px-4 py-3"><Badge variant={criterion.decision ? "secondary" : "outline"}>{criterion.decision ?? "pendente"}</Badge></td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{linked.map((item) => <Badge key={item.id} variant="outline">{item.stableId}</Badge>)}{linked.length === 0 && "—"}</div></td><td className="px-4 py-3">{verified ? <span className="flex items-center gap-1 text-emerald-700 dark:text-emerald-400"><CheckCircle2 className="h-4 w-4" />Verificada</span> : <span className="flex items-center gap-1 text-muted-foreground"><CircleDashed className="h-4 w-4" />Pendente</span>}</td></tr>; })}</tbody></table></CardContent></Card>;
}
