import { useCallback, useEffect, useState } from "react";
import { FileArchive, FileText, Layers3, Loader2, Plus, ReceiptText } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent } from "@/components/ui/card"; import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { createApfMeasurementBatch, getApfAuditPackageData, listApfMeasurementBatches, submitApfBatchForBilling, transitionApfMeasurementBatch } from "../../services/apfEvidenceDossier.service";
import { downloadApfAuditPdf, downloadApfAuditZip } from "../../utils/apfAuditPackage";
import type { ApfEvidenceDossierSummary, ApfMeasurementBatch } from "../../types/apfEvidenceDossier.types";

export function ApfMeasurementBatches({ organizationId, dossiers }: { organizationId: string; dossiers: ApfEvidenceDossierSummary[] }) {
  const [batches,setBatches]=useState<ApfMeasurementBatch[]>([]); const [open,setOpen]=useState(false); const [code,setCode]=useState(""); const [competence,setCompetence]=useState(new Date().toISOString().slice(0,7)+"-01"); const [selected,setSelected]=useState<string[]>([]); const [saving,setSaving]=useState(false); const [exporting,setExporting]=useState<string|null>(null);
  const [billingBatch,setBillingBatch]=useState<ApfMeasurementBatch|null>(null); const [unitPrice,setUnitPrice]=useState(""); const [dueDate,setDueDate]=useState(""); const [billingNote,setBillingNote]=useState("");
  const load=useCallback(async()=>setBatches(await listApfMeasurementBatches(organizationId)),[organizationId]); useEffect(()=>{void load();},[load]);
  const first=dossiers.find(d=>d.id===selected[0]); const eligible=dossiers.filter(d=>d.status==="homologated"&&(!first||(d.contractId===first.contractId&&d.projectId===first.projectId)));
  const create=async()=>{if(!first)return;setSaving(true);try{await createApfMeasurementBatch(organizationId,first.contractId,first.projectId,competence,code,selected);toast.success("Lote de medição criado.");setOpen(false);setSelected([]);setCode("");await load();}catch(error){toast.error(error instanceof Error?error.message:"Falha ao criar lote.");}finally{setSaving(false);}};
  const advance=async(batch:ApfMeasurementBatch)=>{const decision=batch.status==="draft"?"submitted":batch.status==="under_review"?"approved":batch.status==="approved"||batch.status==="glosa_resolved"?"closed":null;if(!decision)return;const note=window.prompt("Justificativa da decisão");if(!note?.trim())return;try{await transitionApfMeasurementBatch(batch.id,decision,note);await load();toast.success("Workflow atualizado.");}catch(error){toast.error(error instanceof Error?error.message:"Falha na transição.");}};
  const exportPackage=async(batchId:string,format:"zip"|"pdf")=>{setExporting(`${batchId}:${format}`);try{const data=await getApfAuditPackageData(batchId);if(format==="zip")await downloadApfAuditZip(data);else await downloadApfAuditPdf(data);toast.success("Pacote de auditoria gerado.");}catch(error){toast.error(error instanceof Error?error.message:"Falha ao gerar pacote.");}finally{setExporting(null);}};
  const submitBilling=async()=>{if(!billingBatch)return;setSaving(true);try{await submitApfBatchForBilling(billingBatch.id,Number(unitPrice),dueDate,billingNote);toast.success("Lote enviado ao faturamento.");setBillingBatch(null);setUnitPrice("");setDueDate("");setBillingNote("");await load();}catch(error){toast.error(error instanceof Error?error.message:"Falha ao enviar ao faturamento.");}finally{setSaving(false);}};
  return <section className="space-y-3" aria-labelledby="batches-title"><div className="flex items-center justify-between"><div><h3 id="batches-title" className="font-semibold">Consolidação por competência</h3><p className="text-sm text-muted-foreground">Lotes imutáveis de dossiês homologados para aprovação e faturamento.</p></div><Button variant="outline" onClick={()=>setOpen(true)} disabled={!dossiers.some(d=>d.status==="homologated")}><Plus className="mr-2 h-4 w-4"/>Novo lote</Button></div>
  {batches.length===0?<Card className="border-dashed"><CardContent className="py-6 text-center text-sm text-muted-foreground"><Layers3 className="mx-auto mb-2 h-6 w-6"/>Nenhum lote consolidado.</CardContent></Card>:<div className="grid gap-2 md:grid-cols-2">{batches.map(batch=><Card key={batch.id}><CardContent className="flex items-center gap-3 p-4"><div className="flex-1"><div className="flex flex-wrap gap-2"><strong>{batch.code}</strong><Badge variant="outline">{batch.status}</Badge>{batch.billingStatus&&<Badge>Faturamento: {batch.billingStatus}</Badge>}</div><p className="text-xs text-muted-foreground">{batch.competence.slice(0,7)} · {batch.dossierCount} dossiê(s)</p></div><div className="text-right"><p className="font-semibold">{batch.totalPf.toLocaleString("pt-BR")} PF</p><div className="flex justify-end"><Button variant="ghost" size="icon" aria-label="Exportar ZIP" onClick={()=>void exportPackage(batch.id,"zip")} disabled={exporting!==null}><FileArchive className="h-4 w-4"/></Button><Button variant="ghost" size="icon" aria-label="Exportar PDF" onClick={()=>void exportPackage(batch.id,"pdf")} disabled={exporting!==null}><FileText className="h-4 w-4"/></Button>{!batch.billingStatus&&["approved","glosa_resolved","closed"].includes(batch.status)&&<Button variant="ghost" size="icon" aria-label="Enviar ao faturamento" onClick={()=>setBillingBatch(batch)}><ReceiptText className="h-4 w-4"/></Button>}<Button variant="ghost" size="sm" onClick={()=>void advance(batch)}>Avançar</Button></div></div></CardContent></Card>)}</div>}
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Novo lote de medição</DialogTitle><DialogDescription>Selecione dossiês homologados do mesmo contrato e projeto.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Código</Label><Input value={code} onChange={e=>setCode(e.target.value)} placeholder="MED-2026-08"/></div><div><Label>Competência</Label><Input type="month" value={competence.slice(0,7)} onChange={e=>setCompetence(e.target.value+"-01")}/></div><fieldset className="space-y-2"><legend className="text-sm font-medium">Dossiês</legend>{eligible.map(d=><label key={d.id} className="flex items-center gap-2 rounded border p-2 text-sm"><Checkbox checked={selected.includes(d.id)} onCheckedChange={checked=>setSelected(all=>checked?[...all,d.id]:all.filter(id=>id!==d.id))}/>{d.dossierCode} · {d.totalHomologatedPf??d.totalImpactedPf} PF</label>)}</fieldset></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={saving||!code.trim()||!selected.length} onClick={()=>void create()}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Criar lote</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(billingBatch)} onOpenChange={value=>!value&&setBillingBatch(null)}><DialogContent><DialogHeader><DialogTitle>Enviar lote ao faturamento</DialogTitle><DialogDescription>{billingBatch?.code}: serão faturados {Math.max((billingBatch?.totalPf??0)-(billingBatch?.disputedPf??0),0).toLocaleString("pt-BR")} PF líquidos.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label htmlFor="apf-unit-price">Preço por PF (R$)</Label><Input id="apf-unit-price" type="number" min="0" step="0.01" value={unitPrice} onChange={e=>setUnitPrice(e.target.value)}/></div><div><Label htmlFor="apf-due-date">Vencimento</Label><Input id="apf-due-date" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></div><div><Label htmlFor="apf-billing-note">Observação</Label><Input id="apf-billing-note" value={billingNote} onChange={e=>setBillingNote(e.target.value)}/></div>{billingBatch&&unitPrice&&<p className="rounded bg-muted p-3 text-sm">Valor previsto: {(Math.max(billingBatch.totalPf-billingBatch.disputedPf,0)*Number(unitPrice)).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p>}</div><DialogFooter><Button variant="outline" onClick={()=>setBillingBatch(null)}>Cancelar</Button><Button disabled={saving||!dueDate||unitPrice===""||Number(unitPrice)<0} onClick={()=>void submitBilling()}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Enviar</Button></DialogFooter></DialogContent></Dialog></section>;
}
