import { useCallback, useEffect, useState } from "react";
import { Layers3, Loader2, Plus } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent } from "@/components/ui/card"; import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { createApfMeasurementBatch, listApfMeasurementBatches, transitionApfMeasurementBatch } from "../../services/apfEvidenceDossier.service";
import type { ApfEvidenceDossierSummary, ApfMeasurementBatch } from "../../types/apfEvidenceDossier.types";

export function ApfMeasurementBatches({ organizationId, dossiers }: { organizationId: string; dossiers: ApfEvidenceDossierSummary[] }) {
  const [batches,setBatches]=useState<ApfMeasurementBatch[]>([]); const [open,setOpen]=useState(false); const [code,setCode]=useState(""); const [competence,setCompetence]=useState(new Date().toISOString().slice(0,7)+"-01"); const [selected,setSelected]=useState<string[]>([]); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>setBatches(await listApfMeasurementBatches(organizationId)),[organizationId]); useEffect(()=>{void load();},[load]);
  const first=dossiers.find(d=>d.id===selected[0]); const eligible=dossiers.filter(d=>d.status==="homologated"&&(!first||(d.contractId===first.contractId&&d.projectId===first.projectId)));
  const create=async()=>{if(!first)return;setSaving(true);try{await createApfMeasurementBatch(organizationId,first.contractId,first.projectId,competence,code,selected);toast.success("Lote de medição criado.");setOpen(false);setSelected([]);setCode("");await load();}catch(error){toast.error(error instanceof Error?error.message:"Falha ao criar lote.");}finally{setSaving(false);}};
  const advance=async(batch:ApfMeasurementBatch)=>{const decision=batch.status==="draft"?"submitted":batch.status==="under_review"?"approved":batch.status==="approved"||batch.status==="glosa_resolved"?"closed":null;if(!decision)return;const note=window.prompt("Justificativa da decisão");if(!note?.trim())return;try{await transitionApfMeasurementBatch(batch.id,decision,note);await load();toast.success("Workflow atualizado.");}catch(error){toast.error(error instanceof Error?error.message:"Falha na transição.");}};
  return <section className="space-y-3" aria-labelledby="batches-title"><div className="flex items-center justify-between"><div><h3 id="batches-title" className="font-semibold">Consolidação por competência</h3><p className="text-sm text-muted-foreground">Lotes imutáveis de dossiês homologados para aprovação e faturamento.</p></div><Button variant="outline" onClick={()=>setOpen(true)} disabled={!dossiers.some(d=>d.status==="homologated")}><Plus className="mr-2 h-4 w-4"/>Novo lote</Button></div>
  {batches.length===0?<Card className="border-dashed"><CardContent className="py-6 text-center text-sm text-muted-foreground"><Layers3 className="mx-auto mb-2 h-6 w-6"/>Nenhum lote consolidado.</CardContent></Card>:<div className="grid gap-2 md:grid-cols-2">{batches.map(batch=><Card key={batch.id}><CardContent className="flex items-center gap-3 p-4"><div className="flex-1"><div className="flex gap-2"><strong>{batch.code}</strong><Badge variant="outline">{batch.status}</Badge></div><p className="text-xs text-muted-foreground">{batch.competence.slice(0,7)} · {batch.dossierCount} dossiê(s)</p></div><div className="text-right"><p className="font-semibold">{batch.totalPf.toLocaleString("pt-BR")} PF</p><Button variant="ghost" size="sm" onClick={()=>void advance(batch)}>Avançar</Button></div></CardContent></Card>)}</div>}
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Novo lote de medição</DialogTitle><DialogDescription>Selecione dossiês homologados do mesmo contrato e projeto.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Código</Label><Input value={code} onChange={e=>setCode(e.target.value)} placeholder="MED-2026-08"/></div><div><Label>Competência</Label><Input type="month" value={competence.slice(0,7)} onChange={e=>setCompetence(e.target.value+"-01")}/></div><fieldset className="space-y-2"><legend className="text-sm font-medium">Dossiês</legend>{eligible.map(d=><label key={d.id} className="flex items-center gap-2 rounded border p-2 text-sm"><Checkbox checked={selected.includes(d.id)} onCheckedChange={checked=>setSelected(all=>checked?[...all,d.id]:all.filter(id=>id!==d.id))}/>{d.dossierCode} · {d.totalHomologatedPf??d.totalImpactedPf} PF</label>)}</fieldset></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={saving||!code.trim()||!selected.length} onClick={()=>void create()}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Criar lote</Button></DialogFooter></DialogContent></Dialog></section>;
}
