create table public.apf_measurement_batches(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,contract_id uuid not null references public.contracts(id) on delete restrict,project_id uuid references public.projects(id) on delete restrict,
 competence date not null,code text not null,status text not null default'draft'check(status in('draft','under_review','approved','glosa_requested','glosa_resolved','closed','cancelled')),
 total_pf numeric(14,4)not null default 0,disputed_pf numeric(14,4)not null default 0,created_by uuid not null default auth.uid()references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code)
);
create table public.apf_measurement_batch_dossiers(batch_id uuid not null references public.apf_measurement_batches(id)on delete cascade,dossier_id uuid not null references public.apf_evidence_dossiers(id)on delete restrict,pf_snapshot numeric(12,4)not null,content_hash text not null,added_by uuid not null default auth.uid()references auth.users(id),added_at timestamptz not null default now(),primary key(batch_id,dossier_id));
create table public.apf_measurement_batch_decisions(id bigint generated always as identity primary key,batch_id uuid not null references public.apf_measurement_batches(id)on delete restrict,decision text not null check(decision in('submitted','approved','glosa_requested','glosa_resolved','closed','cancelled')),note text not null,disputed_pf numeric(14,4),actor_id uuid not null default auth.uid()references auth.users(id),created_at timestamptz not null default now());
alter table public.apf_measurement_batches enable row level security;alter table public.apf_measurement_batch_dossiers enable row level security;alter table public.apf_measurement_batch_decisions enable row level security;
create policy apf_batches_select on public.apf_measurement_batches for select to authenticated using(public.is_organization_member(organization_id,auth.uid()));
create policy apf_batch_dossiers_select on public.apf_measurement_batch_dossiers for select to authenticated using(exists(select 1 from public.apf_measurement_batches b where b.id=batch_id and public.is_organization_member(b.organization_id,auth.uid())));
create policy apf_batch_decisions_select on public.apf_measurement_batch_decisions for select to authenticated using(exists(select 1 from public.apf_measurement_batches b where b.id=batch_id and public.is_organization_member(b.organization_id,auth.uid())));

create or replace function public.create_apf_measurement_batch(p_organization_id uuid,p_contract_id uuid,p_project_id uuid,p_competence date,p_code text,p_dossier_ids uuid[])returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare bid uuid;did uuid;d public.apf_evidence_dossiers%rowtype;v public.apf_dossier_versions%rowtype;
begin
 if auth.uid()is null or not public.is_organization_member(p_organization_id,auth.uid())then raise exception'Acesso negado.'using errcode='42501';end if;
 if nullif(trim(p_code),'')is null or coalesce(array_length(p_dossier_ids,1),0)=0 then raise exception'Código e dossiês são obrigatórios.'using errcode='22023';end if;
 insert into public.apf_measurement_batches(organization_id,contract_id,project_id,competence,code)values(p_organization_id,p_contract_id,p_project_id,date_trunc('month',p_competence)::date,trim(p_code))returning id into bid;
 foreach did in array p_dossier_ids loop select*into d from public.apf_evidence_dossiers where id=did and organization_id=p_organization_id and contract_id=p_contract_id and status='homologated';if not found then raise exception'Dossiê não homologado ou fora do lote.'using errcode='22023';end if;if p_project_id is not null and d.project_id<>p_project_id then raise exception'Dossiê pertence a outro projeto.'using errcode='22023';end if;select*into v from public.apf_dossier_versions where dossier_id=did order by version_number desc limit 1;insert into public.apf_measurement_batch_dossiers values(bid,did,coalesce(d.total_homologated_pf,d.total_impacted_pf),v.content_hash,auth.uid(),now());end loop;
 update public.apf_measurement_batches set total_pf=(select sum(pf_snapshot)from public.apf_measurement_batch_dossiers where batch_id=bid)where id=bid;return bid;
end $$;
create or replace function public.transition_apf_measurement_batch(p_batch_id uuid,p_decision text,p_note text,p_disputed_pf numeric default null)returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare b public.apf_measurement_batches%rowtype;next_status text;
begin select*into b from public.apf_measurement_batches where id=p_batch_id for update;if not found or auth.uid()is null or not public.is_organization_member(b.organization_id,auth.uid())then raise exception'Acesso negado.'using errcode='42501';end if;if nullif(trim(p_note),'')is null then raise exception'Justificativa obrigatória.'using errcode='22023';end if;
 next_status:=case when b.status='draft'and p_decision='submitted'then'under_review'when b.status='under_review'and p_decision='approved'then'approved'when b.status in('under_review','approved')and p_decision='glosa_requested'then'glosa_requested'when b.status='glosa_requested'and p_decision='glosa_resolved'then'glosa_resolved'when b.status in('approved','glosa_resolved')and p_decision='closed'then'closed'when b.status not in('closed','cancelled')and p_decision='cancelled'then'cancelled'end;if next_status is null then raise exception'Transição inválida.'using errcode='22023';end if;
 update public.apf_measurement_batches set status=next_status,disputed_pf=case when p_decision='glosa_requested'then coalesce(p_disputed_pf,0)when p_decision='glosa_resolved'then coalesce(p_disputed_pf,0)else disputed_pf end,updated_at=now()where id=p_batch_id;insert into public.apf_measurement_batch_decisions(batch_id,decision,note,disputed_pf)values(p_batch_id,p_decision,trim(p_note),p_disputed_pf);
end $$;
revoke all on function public.create_apf_measurement_batch(uuid,uuid,uuid,date,text,uuid[])from public;revoke all on function public.transition_apf_measurement_batch(uuid,text,text,numeric)from public;grant execute on function public.create_apf_measurement_batch(uuid,uuid,uuid,date,text,uuid[])to authenticated;grant execute on function public.transition_apf_measurement_batch(uuid,text,text,numeric)to authenticated;
